### ISSUE TITLE
'str' type is not used in CWL v1.0.20161128202906 (RDFLib 4.2.1)

### ISSUE THREAD

**Issue by MatthewRalston** [erasche/argparse2tool#35]
While following the [CWL v1.0 spec](http://www.commonwl.org/v1.0/UserGuide.html#First_example), I was implementing a hello world example python script, and figured i'd try out argparse2tool. The generated yml seems to be inconsistent with the v1.0 spec. Changing 'str' to 'string' in the yaml seems to fix the issue.

error:
```bash
...
Resolved 'hello_world.yml' to file:///home/MatthewRalston/sandbox/Toil/hello_world.yml'
INFO:cwltool:resolve 'hello_world.yml' to 'file:///home/MatthewRalston/sandbox/Toil/hello_world.yml'
Tool definition failed validation:
While checking field `inputs`
  While checking object `file:///home/MatthewRalston/sandbox/Toil/hello_world.yml#message`
    Field `type` contains undefined reference to `str`, tried  [u'file:///home/MatthewRalston/sandbox/Toil/hello_world.yml#str']
ERROR:cwltool:Tool definition failed validation:
While checking field `inputs`
  While checking object `file:///home/MatthewRalston/sandbox/Toil/hello_world.yml#message`
    Field `type` contains undefined reference to `str`, tried  [u'file:///home/MatthewRalston/sandbox/Toil/hello_world.yml#str']
```

hello_world.py
```python
...
parser.add_argument('--message', help="Required argument", required=True)
parser.add_argument('--flag', help="This is a flag", action="store_true")
...
```

`--help`/usage info

```bash
usage: hello_world.py [-h] --message MESSAGE [--flag]

optional arguments:
  -h, --help                       show this help message and exit
  --message MESSAGE     Required argument (default: None)
  --flag                              This is a flag (default: False)
```

Generated yml:
```yaml
inputs:

  message:
    type: str
    doc: Required argument
    inputBinding:
      prefix: --message

  flag:
    type: ["null", boolean]
    default: False
    doc: This is a flag
    inputBinding:
      prefix: --flag

```
